# Generated by Django 5.0.4 on 2024-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_userplan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan',
            field=models.CharField(blank=True, choices=[('free_tier', 'Free tier'), ('basic', 'Basic'), ('premium', 'Premium'), ('plus', 'Plus')], max_length=200, null=True, verbose_name='plan'),
        ),
    ]
