# Generated by Django 5.0.4 on 2024-04-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plans_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='plan'),
        ),
    ]
